version: "3.9"
services:
  db:
    image: postgres:16
    container_name: alsapp_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: als
      POSTGRES_PASSWORD: als_pass
      POSTGRES_DB: alsapp
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: